/* ============================================================
   kiosk.js — auto-advancing dashboard for unattended display.

   Cycles through the six top-level tabs on a 15s tick. After each full
   pass, a full-screen "AD" summarises the most important thing from one
   tab; ADs rotate evenly one per pass so every tab gets equal airtime.

   Only one setTimeout is ever live — the state machine reschedules itself
   at each transition rather than running an interval alongside the tick.

   Manual interaction pauses everything and the cycle resumes 20 seconds
   after the last real pointer or key event; the skip button (bottom-left,
   always visible while kiosk is on) is exempt and just jumps to the next
   AD without pausing.
   ============================================================ */

const Kiosk = (() => {

  const TABS = ['calendar','sports','portfolio','movies','notes','fantasy'];
  const TAB_MS = 15000;
  const AD_MS  = 30000;
  const RESUME_MS = 20000;

  let enabled  = false;
  let mode     = 'tab';        // 'tab' | 'ad'
  let tabIdx   = 0;
  let adIdx    = 0;
  let timerId  = null;
  let pausedUntil = 0;

  /* One cursor per sub-selecting tab. Read modulo current list length so a
     team added or removed at runtime wraps cleanly rather than throwing or
     skipping. */
  const subCursor = {sports:0, portfolio:0};

  const overlay = () => document.getElementById('adOverlay');
  const skipBtn = () => document.getElementById('kioskSkip');
  const toggleBtn = () => document.getElementById('kioskToggle');

  /* ---- timer plumbing ---- */
  function clearTimer(){
    if(timerId){ clearTimeout(timerId); timerId = null; }
  }

  function schedule(ms){
    clearTimer();
    if(!enabled) return;
    timerId = setTimeout(tick, ms);
  }

  /* ---- state machine ---- */
  function tick(){
    if(!enabled) return;

    /* Interaction may have landed since this timer was armed; honour the
       pause instead of firing on top of a user still using the deck. */
    const wait = pausedUntil - Date.now();
    if(wait > 0){ schedule(wait); return; }

    if(mode === 'ad'){
      closeAd();
      mode = 'tab';
      tabIdx = 0;
      adIdx = (adIdx + 1) % TABS.length;
      showCurrentTab();
      schedule(TAB_MS);
      return;
    }

    tabIdx++;
    if(tabIdx >= TABS.length){
      mode = 'ad';
      openAd(TABS[adIdx]);
      schedule(AD_MS);
    } else {
      showCurrentTab();
      schedule(TAB_MS);
    }
  }

  function showCurrentTab(){
    const name = TABS[tabIdx];
    try{ App.showTab(name); }
    catch(e){ console.error('Kiosk showTab failed:', e); }
    /* Give the tab a paint frame before touching its sub-tabs — the sub-tab
       list is regenerated by that tab's render(). */
    setTimeout(() => applySubCursor(name), 60);
  }

  function applySubCursor(name){
    if(name === 'sports'){
      const btns = document.querySelectorAll('#teamTabs .subtab[data-team]');
      if(!btns.length) return;
      const i = subCursor.sports % btns.length;
      programmaticClick(btns[i]);
      subCursor.sports = (i + 1) % btns.length;
    } else if(name === 'portfolio'){
      const btns = document.querySelectorAll('#pfAccounts .subtab[data-acct]');
      if(btns.length < 2) return;   // 'All' alone isn't a rotation
      const i = subCursor.portfolio % btns.length;
      programmaticClick(btns[i]);
      subCursor.portfolio = (i + 1) % btns.length;
    }
  }

  /* A dispatched click fires the button's own handler but not our
     interaction listener (which listens for pointerdown/keydown), so
     rotating the sub-tabs does not look like a user interruption. */
  function programmaticClick(el){
    try{ el.click(); } catch(e){ /* button removed mid-tick — ignore */ }
  }

  /* ---- start / stop / toggle ---- */
  function start(){
    if(enabled) return;
    enabled = true;
    Store.set('kiosk.enabled', true);
    document.body.classList.add('kiosk-on');
    updateToggleUi();
    /* Reset to the beginning of the cycle so a fresh start is predictable —
       the user just enabled it, they should see it begin. */
    mode = 'tab';
    tabIdx = 0;
    subCursor.sports = 0;
    subCursor.portfolio = 0;
    showCurrentTab();
    schedule(TAB_MS);
  }

  function stop(){
    enabled = false;
    Store.set('kiosk.enabled', false);
    document.body.classList.remove('kiosk-on');
    clearTimer();
    closeAd();
    updateToggleUi();
  }

  function toggle(){ enabled ? stop() : start(); }

  function updateToggleUi(){
    const b = toggleBtn();
    if(!b) return;
    b.textContent = enabled ? 'AUTO ON' : 'AUTO';
    b.classList.toggle('is-on', enabled);
    b.title = enabled ? 'Rotation on — click to stop' : 'Start rotation';
    const s = skipBtn();
    if(s) s.hidden = !enabled;
  }

  /* ---- interaction detection ---- */
  function noteInteraction(){
    if(!enabled) return;
    pausedUntil = Date.now() + RESUME_MS;
    /* If an AD is up when the user touches the screen, get out of the way
       immediately rather than making them wait for the ad timer. */
    if(mode === 'ad') closeAd();
    schedule(RESUME_MS);
  }

  /* ---- skip button ---- */
  function skipToAd(){
    if(!enabled) return;
    /* Jump straight to the next AD, regardless of where we are in the pass.
       This is a control, not an interruption — it should not trigger the
       resume-after-idle pause. */
    closeAd();
    mode = 'ad';
    openAd(TABS[adIdx]);
    schedule(AD_MS);
  }

  /* ---- AD overlay ---- */
  function openAd(name){
    const el = overlay();
    if(!el) return;
    el.className = `ad ad-${name} is-on`;
    el.innerHTML = `<div class="ad-brand">${name.toUpperCase()}</div>
                    <div class="ad-body" id="adBody">
                      <p class="ad-empty">Loading…</p>
                    </div>`;
    renderAd(name);
  }

  function closeAd(){
    const el = overlay();
    if(!el) return;
    el.className = 'ad';
    el.innerHTML = '';
  }

  function renderAd(name){
    const body = document.getElementById('adBody');
    if(!body) return;
    try{
      const fn = AD_RENDERERS[name];
      if(fn) fn(body);
      else body.innerHTML = `<p class="ad-empty">Nothing to show.</p>`;
    }catch(e){
      console.error(`AD "${name}" failed:`, e);
      body.innerHTML = `<p class="ad-empty">Nothing to show right now.</p>`;
    }
  }

  /* ============================================================
     AD renderers — one per tab, single topic, glanceable typography.
     Every renderer degrades to a clean empty state rather than a
     blank overlay.
     ============================================================ */

  const AD_RENDERERS = {
    calendar: adCalendar,
    sports:   adSports,
    portfolio:adPortfolio,
    movies:   adMovies,
    notes:    adNotes,
    fantasy:  adFantasy
  };

  const sameDay = (a,b) => a && b &&
    a.getFullYear() === b.getFullYear() &&
    a.getMonth() === b.getMonth() &&
    a.getDate() === b.getDate();

  function adCalendar(host){
    const today = new Date();
    const events = (window.Calendar ? Calendar.events : [])
      .filter(e => e.start && sameDay(new Date(e.start), today))
      .slice(0, 8);

    if(!events.length){
      host.innerHTML = `<div class="ad-hero">
        <h1 class="ad-h1">${today.toLocaleDateString(undefined,{weekday:'long'})}</h1>
        <p class="ad-sub">${today.toLocaleDateString(undefined,{month:'long',day:'numeric'})}</p>
        <p class="ad-empty ad-big">Nothing on the calendar today.</p>
      </div>`;
      return;
    }

    host.innerHTML = `
      <div class="ad-hero">
        <h1 class="ad-h1">Today</h1>
        <p class="ad-sub">${today.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</p>
      </div>
      <ul class="ad-list">${events.map(e => {
        const t = new Date(e.start);
        const when = e.allDay ? 'All day'
                    : t.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'});
        return `<li class="ad-row">
          <span class="ad-time">${esc(when)}</span>
          <span class="ad-title">${esc(e.title)}</span>
          ${e.where ? `<span class="ad-where">${esc(e.where)}</span>` : ''}
        </li>`;
      }).join('')}</ul>`;
  }

  function adSports(host){
    /* Teams.games already carries "next upcoming or most recent today" per
       team — perfect scope for one glance. Nearest in time to now wins;
       fall back to the most recent past game if none upcoming. */
    const games = (window.Teams ? Teams.games : []) || [];
    if(!games.length){
      host.innerHTML = `<p class="ad-empty ad-big">No games scheduled for followed teams.</p>`;
      return;
    }
    const now = Date.now();
    const upcoming = games
      .filter(g => new Date(g.kickoff).getTime() >= now - 4*36e5)
      .sort((a,b) => new Date(a.kickoff) - new Date(b.kickoff));
    const past = games
      .filter(g => g.state === 'post')
      .sort((a,b) => new Date(b.kickoff) - new Date(a.kickoff));

    const g = upcoming[0] || past[0];
    if(!g){ host.innerHTML = `<p class="ad-empty ad-big">No games right now.</p>`; return; }

    const kick = new Date(g.kickoff);
    const when = g.state === 'in'   ? `LIVE ${g.score}`
              : g.state === 'post' ? `Final ${g.score} · ${g.result === 'win' ? 'W' : 'L'}`
              : kick.toLocaleString(undefined,{weekday:'long',hour:'numeric',minute:'2-digit'});
    const day = sameDay(kick, new Date()) ? 'Today'
              : kick.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});

    const logo = Sports.logoFor({league:g.league, id:g.id});

    host.innerHTML = `
      <div class="ad-hero">
        <h1 class="ad-h1">${esc(g.abbr || g.name)} ${g.home ? 'vs' : '@'} ${esc(g.opponent)}</h1>
        <p class="ad-sub">${esc(Sports.leagueName(g.league))} · ${esc(day)}</p>
      </div>
      <div class="ad-game">
        <img class="ad-game-logo" src="${esc(logo)}" alt="">
        <div class="ad-game-meta">
          <p class="ad-big ${g.state === 'in' ? 'ad-live' : ''}">${esc(when)}</p>
          ${g.venue ? `<p class="ad-sub">${esc(g.venue)}</p>` : ''}
        </div>
      </div>`;
  }

  function adPortfolio(host){
    /* Today's percent change is the return over the previous close, which
       Finnhub's quote endpoint has already given us — dp is per-holding, so
       weight to portfolio percent rather than averaging. */
    const hold = Store.get('holdings',[]);
    const movers = (window.Stocks ? Stocks.movers : []) || [];
    if(!hold.length || !movers.length){
      host.innerHTML = `<p class="ad-empty ad-big">No quotes priced today.</p>`;
      return;
    }

    /* Approximate portfolio-weighted today's return.
       Best-effort: without exposing the internal weight calc, use straight
       average of dp values as a headline. */
    const dps = movers.map(m => m.dp).filter(x => x != null);
    const avg = dps.length ? dps.reduce((s,x) => s + x, 0) / dps.length : 0;
    const sign = avg >= 0 ? '+' : '−';

    const gainers = [...movers].filter(m => m.dp > 0).sort((a,b) => b.dp - a.dp).slice(0, 5);

    host.innerHTML = `
      <div class="ad-hero">
        <h1 class="ad-h1 ${avg >= 0 ? 'ad-up' : 'ad-down'}">${sign}${Math.abs(avg).toFixed(2)}%</h1>
        <p class="ad-sub">Today across ${dps.length} holdings</p>
      </div>
      <div class="ad-cols">
        <div class="ad-col">
          <h3 class="ad-h3">Top gainers</h3>
          <ul class="ad-list">${gainers.length ? gainers.map(m => `
            <li class="ad-row">
              <span class="ad-title">${esc(m.symbol)}</span>
              <span class="ad-up ad-big-sm">+${m.dp.toFixed(2)}%</span>
            </li>`).join('') : '<li class="ad-empty">Nothing green today.</li>'}</ul>
        </div>
      </div>`;
  }

  function adMovies(host){
    /* 80% next-two-weeks upcoming, 20% Letterboxd watchlist. Pick fresh
       each AD so a long uptime cycles through the shelf. */
    const now = Date.now();
    const soon = ((window.Movies ? Movies.upcoming : []) || [])
      .filter(f => f.date && (new Date(f.date + 'T12:00:00').getTime() - now) < 14*864e5 &&
                              new Date(f.date + 'T12:00:00').getTime() > now - 864e5);
    const watch = (window.Letterboxd ? Letterboxd.decorated() : []) || [];

    const pool = (Math.random() < 0.2 && watch.length) ? 'watch'
               : soon.length ? 'soon' : (watch.length ? 'watch' : null);

    if(!pool){
      host.innerHTML = `<p class="ad-empty ad-big">No films to preview.</p>`;
      return;
    }

    let title, year, overview, cast, director, poster;
    if(pool === 'soon'){
      const pick = soon[Math.floor(Math.random() * soon.length)];
      const full = window.Movies ? Movies.byId(pick.id) : null;
      title = pick.title;
      year  = (pick.date || '').slice(0,4);
      poster = pick.poster ? `https://image.tmdb.org/t/p/w500${pick.poster}`
                           : (full?.poster ? `https://image.tmdb.org/t/p/w500${full.poster}` : '');
      overview = full?.overview || '';
      cast = full?.cast || [];
      director = full?.director || '';
    } else {
      const pick = watch[Math.floor(Math.random() * watch.length)];
      title = pick.title;
      year  = pick.year || '';
      poster = pick.poster || '';
      overview = pick.overview || '';
      cast = [];
      director = '';
    }

    host.innerHTML = `
      <div class="ad-movie">
        ${poster
          ? `<img class="ad-poster" src="${esc(poster)}" alt="">`
          : `<div class="ad-poster ad-noart">🎬</div>`}
        <div class="ad-movie-info">
          <h1 class="ad-h1">${esc(title)}</h1>
          <p class="ad-sub">${esc(String(year))}${pool === 'soon' ? ' · Coming soon' : ' · Watchlist'}</p>
          ${director ? `<p class="ad-line"><i>Directed by</i> ${esc(director)}</p>` : ''}
          ${cast.length ? `<p class="ad-line"><i>Starring</i> ${esc(cast.join(', '))}</p>` : ''}
          <p class="ad-overview">${esc(overview) || 'No synopsis available.'}</p>
        </div>
      </div>`;
  }

  function adNotes(host){
    const todayKey = keyOf(new Date());
    const all = Store.get('notes', []) || [];
    /* Closest note whose day is today or later and that is still open. */
    const upcoming = all
      .filter(n => n.day && !n.done && n.day >= todayKey)
      .sort((a,b) => (a.day || '').localeCompare(b.day || ''));

    if(!upcoming.length){
      host.innerHTML = `<p class="ad-empty ad-big">No upcoming notes.</p>`;
      return;
    }
    const n = upcoming[0];
    const day = new Date(n.day + 'T12:00:00');
    const when = sameDay(day, new Date()) ? 'Today'
               : day.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});
    const days = Math.round((day - new Date(new Date().toDateString())) / 864e5);
    const rel = days === 0 ? 'today' : days === 1 ? 'tomorrow' : `in ${days} days`;

    host.innerHTML = `
      <div class="ad-note-card" style="--note:${esc(n.color || 'var(--accent)')}">
        <p class="ad-sub">${esc(when)} · ${esc(rel)}</p>
        <p class="ad-note-text">${esc(n.text || '(empty note)')}</p>
      </div>`;
  }

  function adFantasy(host){
    /* Thu–Mon (day 4,5,6,0,1) shows the current matchup. Tue–Wed (2,3)
       shows the future matchup — the next week's board is what the user
       is planning for on those mid-week days. */
    const dow = new Date().getDay();
    const isFuture = dow === 2 || dow === 3;
    host.innerHTML = `<p class="ad-empty ad-big">Loading matchup…</p>`;

    if(!window.Fantasy || !Store.get('fantasy.league','')){
      host.innerHTML = `<p class="ad-empty ad-big">Fantasy not set up.</p>`;
      return;
    }

    Fantasy.matchup({weekOffset: isFuture ? 1 : 0})
      .then(m => {
        if(!m){ host.innerHTML = `<p class="ad-empty ad-big">No matchup this week.</p>`; return; }
        const side = s => `
          <div class="ad-ff-side${s.mine ? ' is-mine' : ''}">
            <p class="ad-ff-team">${esc(s.name)}</p>
            <p class="ad-ff-score">${(s.score || 0).toFixed(1)}</p>
            <ul class="ad-ff-top">${(s.top || []).map(p => `
              <li><b>${esc(p.name)}</b> <i>${esc(p.pos)}</i> — ${p.points.toFixed(1)}</li>`).join('')}</ul>
          </div>`;
        host.innerHTML = `
          <div class="ad-hero">
            <h1 class="ad-h1">Week ${m.week}${isFuture ? ' · Preview' : ''}</h1>
            <p class="ad-sub">${isFuture ? 'Next week matchup' : 'Current matchup'}</p>
          </div>
          <div class="ad-ff-vs">${side(m.away)}<span class="ad-ff-dash">vs</span>${side(m.home)}</div>`;
      })
      .catch(e => {
        host.innerHTML = `<p class="ad-empty ad-big">Matchup unavailable (${esc(e.message)}).</p>`;
      });
  }

  const keyOf = d => {
    const x = new Date(d);
    return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`;
  };

  /* ---- wiring ---- */
  function boot(){
    /* Interaction listeners are capture-phase so nothing else can swallow
       them. pointerdown covers mouse+touch+pen in one event. Skip and
       toggle buttons live inside #kioskControls and are excluded. */
    const isInternal = target => !!(target && target.closest &&
      (target.closest('#kioskControls') || target.closest('#kioskToggle')));

    document.addEventListener('pointerdown', e => {
      if(!isInternal(e.target)) noteInteraction();
    }, true);
    document.addEventListener('keydown', e => {
      if(!isInternal(e.target)) noteInteraction();
    }, true);
    document.addEventListener('wheel', e => {
      if(!isInternal(e.target)) noteInteraction();
    }, {capture:true, passive:true});

    const t = toggleBtn();
    if(t) t.addEventListener('click', toggle);
    const s = skipBtn();
    if(s) s.addEventListener('click', skipToAd);

    if(Store.get('kiosk.enabled', false)) start();
    updateToggleUi();
  }

  return { boot, start, stop, toggle, get enabled(){ return enabled; } };
})();

window.Kiosk = Kiosk;
